const $=s=>document.querySelector(s),services=['eGS Standard','eGS Express','eGS EMS'],cats=['일반 상품','의류 · 패션','뷰티 · 화장품','전자기기','도서 · 미디어','완구 · 취미','생활 · 주방','건강 · 식품','기타'],baseCountries=['미국','캐나다','영국','독일','프랑스','이탈리아','스페인','호주','일본','싱가포르','홍콩','대만','멕시코','브라질'],eu=new Set(['독일','프랑스','이탈리아','스페인','네덜란드','벨기에','오스트리아','스웨덴','덴마크','핀란드','폴란드','포르투갈','아일랜드','그리스','체코','헝가리','루마니아','불가리아','크로아티아','슬로바키아','슬로베니아','에스토니아','라트비아','리투아니아','룩셈부르크','몰타','사이프러스']);
let fx=1450,bulk=[];let data=(()=>{try{return JSON.parse(localStorage.getItem('sellscope-rates'))||{rates:[],taxes:[]}}catch{return{rates:[],taxes:[]}}})();
const n=v=>Number(v)||0,clean=v=>String(v??'').trim(),norm=v=>clean(v).replace(/\s+/g,'').toLowerCase(),krw=v=>Number.isFinite(v)?`₩${Math.round(v).toLocaleString('ko-KR')}`:'—',usd=v=>Number.isFinite(v)?`$${v.toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2})}`:'—',name=p=>`${p}_${new Date().toISOString().slice(0,10)}.xlsx`;
function options(){let countries=[...new Set([...baseCountries,...data.rates.map(r=>r.country).filter(Boolean)])].sort((a,b)=>a.localeCompare(b,'ko'));$('#country').innerHTML=countries.map(x=>`<option>${x}</option>`).join('');$('#category').innerHTML=cats.map(x=>`<option>${x}</option>`).join('')}
function status(){let ok=data.rates.length>0;$('#rateStatus').textContent=ok?`${data.rates.length.toLocaleString()}개 요금 구간 · ${(data.taxes||[]).length.toLocaleString()}개 세금 규칙을 불러왔습니다.`:'등록된 요금표가 없습니다.';$('#clearRates').hidden=!ok;$('#bulkRun').disabled=!ok||!bulk.length;$('#rateNotice').innerHTML=ok?`<strong>요금표가 준비됐습니다.</strong><span>${data.updated||'방금'} 불러온 기준으로 계산합니다.</span><button class="link-button" data-action="rates" type="button">요금표 관리 →</button>`:`<strong>요금표를 불러오면 정확히 계산됩니다.</strong><span>제공할 EGS 요금 엑셀을 업로드하거나 양식으로 요금표를 준비해 주세요.</span><button class="link-button" data-action="rates" type="button">요금표 관리 →</button>`}
function form(){return{country:$('#country').value,length:n($('#length').value),width:n($('#width').value),height:n($('#height').value),weight:n($('#weight').value),sale:n($('#salePrice').value),cost:n($('#costPrice').value),pack:n($('#packaging').value),category:$('#category').value,rate:n($('#feeRate').value)/100,fixed:n($('#feeFixed').value)}}
function div(service,country){return service==='eGS Express'||(service==='eGS Standard'&&eu.has(country))?5000:6000}
function ship(v,service){let volume=v.length*v.width*v.height/div(service,v.country),applied=Math.ceil(Math.max(v.weight,volume)*10)/10,row=data.rates.filter(r=>norm(r.country)===norm(v.country)&&norm(r.service)===norm(service)&&n(r.maxWeight)>=applied).sort((a,b)=>n(a.maxWeight)-n(b.maxWeight))[0];return{volume,applied,cost:row?n(row.shippingCost):null}}
function tax(v,shipping){let rules=data.taxes||[],r=rules.filter(x=>norm(x.country)===norm(v.country)&&(norm(x.category)===norm(v.category)||norm(x.category)==='전체')).sort((a,b)=>norm(a.category)===norm(v.category)?-1:1)[0];if(!r)return{total:0,label:'세금 규칙 없음'};let base=v.sale+(shipping||0),threshold=n(r.thresholdUSD);if(base/fx<=threshold)return{total:0,label:`면세 한도 ${usd(threshold)}`};let duty=base*n(r.dutyRate)/100,vat=(base+duty)*n(r.vatRate)/100;return{total:duty+vat,label:'요금표 세금 규칙'}}
function calcOne(v,service){let s=ship(v,service),fee=v.sale*v.rate+v.fixed*fx,t=tax(v,s.cost||0),profit=s.cost==null?null:v.sale-v.cost-v.pack-s.cost-fee-t.total;return{service,...s,fee,t,profit,margin:profit==null||!v.sale?null:profit/v.sale}}
function render(results){let selected=$('#service').value,r=results.find(x=>x.service===selected)||results[0];$('#resultTitle').textContent=r.cost==null?'요금표가 필요합니다':'예상 수익을 계산했어요';$('#resultHelp').textContent=r.cost==null?`${form().country} ${selected} 요금 구간을 찾지 못했습니다.`:`${form().country} · ${selected} 기준 결과입니다.`;$('#shippingCost').textContent=krw(r.cost);$('#shippingService').textContent=r.cost==null?'요금표를 확인하세요':r.service;$('#netProfit').textContent=krw(r.profit);$('#profitUsd').textContent=r.profit==null?'—':usd(r.profit/fx);$('#marginRate').textContent=r.margin==null?'—':`${(r.margin*100).toFixed(1)}%`;$('#volumeWeight').textContent=`${r.volume.toFixed(2)}kg`;$('#ebayFee').textContent=krw(r.fee);$('#taxCost').textContent=krw(r.t.total);$('#appliedInfo').textContent=`실중량과 부피무게 중 큰 무게를 적용합니다. (${r.t.label})`;$('#rateRows').innerHTML=results.map(x=>`<tr><td><b>${x.service}</b></td><td>÷${div(x.service,form().country).toLocaleString()}</td><td>${x.applied.toFixed(1)}kg<br><small>부피 ${x.volume.toFixed(2)}kg</small></td><td><b>${krw(x.cost)}</b></td><td><input class="table-radio" type="radio" name="service-choice" value="${x.service}" ${x.service===selected?'checked':''} ${x.cost==null?'disabled':''}></td></tr>`).join('');document.querySelectorAll('.table-radio').forEach(el=>el.addEventListener('change',e=>{$('#service').value=e.target.value;calculate()}))}
function calculate(){let v=form(),results=services.map(s=>calcOne(v,s));render(results);return{v,results}}
function key(row,...names){let k=Object.keys(row).find(k=>names.some(x=>norm(k)===norm(x)));return k?row[k]:''}
function mapped(row){return{country:clean(key(row,'국가','배송국가','country')),service:clean(key(row,'서비스','service')),maxWeight:n(key(row,'최대적용중량kg','최대중량','maxweightkg')),shippingCost:n(key(row,'배송비원','배송비','shippingcostkrw')),category:clean(key(row,'상품카테고리','카테고리','category')),dutyRate:n(key(row,'관세율','dutyrate')),vatRate:n(key(row,'부가세율','vatrate')),thresholdUSD:n(key(row,'면세한도usd','면세한도','thresholdusd'))}}
function read(file,done){let f=new FileReader();f.onload=e=>done(XLSX.read(e.target.result,{type:'array'}));f.readAsArrayBuffer(file)}
function rows(book,sheet){return book.Sheets[sheet]?XLSX.utils.sheet_to_json(book.Sheets[sheet],{defval:''}):[]}
const isoKo={US:'미국',CA:'캐나다',GB:'영국',AU:'호주',BE:'벨기에',CZ:'체코',FR:'프랑스',DE:'독일',HU:'헝가리',IT:'이탈리아',NL:'네덜란드',PL:'폴란드',PT:'포르투갈',ES:'스페인',AT:'오스트리아',FI:'핀란드',IE:'아일랜드',SE:'스웨덴',DK:'덴마크',GR:'그리스',BG:'불가리아',HR:'크로아티아',CY:'사이프러스',EE:'에스토니아',LV:'라트비아',LT:'리투아니아',LU:'룩셈부르크',MT:'몰타',RO:'루마니아',SK:'슬로바키아',SI:'슬로베니아',JP:'일본',MY:'말레이시아',TH:'태국',PH:'필리핀',ID:'인도네시아',NZ:'뉴질랜드',HK:'홍콩',CN:'중국',TW:'대만',VN:'베트남',IN:'인도',MX:'멕시코',BR:'브라질',SG:'싱가포르',RU:'러시아',AF:'아프가니스탄',AL:'알바니아',DZ:'알제리',AR:'아르헨티나'};
const commonNameKo={'United States':'미국','United Kingdom':'영국','South Korea':'한국','Czech Republic':'체코','Netherlands':'네덜란드','Greece':'그리스','Taiwan':'대만','Hong Kong':'홍콩','Vietnam':'베트남','New Zealand':'뉴질랜드','Philippines':'필리핀','Indonesia':'인도네시아','Singapore':'싱가포르','Malaysia':'말레이시아','Thailand':'태국','Australia':'호주','Canada':'캐나다','Japan':'일본','China':'중국','France':'프랑스','Germany':'독일','Italy':'이탈리아','Spain':'스페인','Portugal':'포르투갈','Poland':'폴란드','Belgium':'벨기에','Austria':'오스트리아','Finland':'핀란드','Ireland':'아일랜드','Sweden':'스웨덴','Denmark':'덴마크','Mexico':'멕시코','Brazil':'브라질','India':'인도','Russia':'러시아'};
function sheetArray(book,name){return book.Sheets[name]?XLSX.utils.sheet_to_json(book.Sheets[name],{header:1,defval:null,blankrows:false}):[]}
function addRate(out,country,service,maxWeight,shippingCost){if(country&&Number(maxWeight)>0&&Number(shippingCost)>0)out.push({country,service,maxWeight:Number(maxWeight),shippingCost:Number(shippingCost)})}
function parseTwoColumn(out,arr,country,service){arr.forEach(row=>addRate(out,country,service,row[1],row[2]))}
function parseEUStandard(out,arr){let headerIndex=arr.findIndex(row=>row.some(value=>String(value||'').trim()==='Country'));if(headerIndex<0)return;let groups=[0,11,22],header=arr[headerIndex];groups.forEach(start=>{for(let col=start+1;col<start+11;col++){let code=String(header[col]||'').match(/[A-Z]{2}/)?.[0],country=isoKo[code];if(!country)continue;for(let row=headerIndex+1;row<arr.length;row++)addRate(out,country,'eGS Standard',arr[row][start],arr[row][col])}})}
function parseExpress(out,book){let tariff=sheetArray(book,'eGS Express'),zones=sheetArray(book,'eGS Express Service Zone'),zoneCountries={};zones.slice(1).forEach(row=>{let iso=String(row[1]||'').trim(),zone=String(row[2]||'').trim(),country=isoKo[iso]||commonNameKo[String(row[0]||'').trim()];if(iso&&zone&&country)zoneCountries[iso]={zone,country}});let headerIndex=tariff.findIndex(row=>row.some(value=>String(value||'').trim()==='Major Destinations'));if(headerIndex<1)return;let letters=tariff[headerIndex-1]||[],headers=tariff[headerIndex]||[],zoneColumn={};headers.forEach((value,col)=>{let letter=String(letters[col]||'').trim();if(letter&&value)zoneColumn[letter]=col});Object.values(zoneCountries).forEach(({zone,country})=>{let col=zoneColumn[zone];if(col===undefined)return;tariff.slice(headerIndex+1).forEach(row=>addRate(out,country,'eGS Express',row[1],row[col]))})}
function parseEMS(out,arr){let headerIndex=arr.findIndex(row=>row.some(value=>String(value||'').trim()==='Weigh(구간)'));if(headerIndex<0)return;let headers=arr[headerIndex],weightCols=headers.map((value,index)=>String(value||'').trim()==='Weigh(구간)'?index:null).filter(index=>index!==null);for(let col=0;col<headers.length;col++){let country=String(headers[col]||'').trim();if(!country||country==='Weigh(구간)'||/^\d지역$/.test(country))continue;let start=[...weightCols].filter(x=>x<=col).pop();arr.slice(headerIndex+1).forEach(row=>addRate(out,country,'eGS EMS',row[start],row[col]))}}
function parseActualEGS(book){let out=[];parseTwoColumn(out,sheetArray(book,'eGS Standard - GB'),'영국','eGS Standard');parseTwoColumn(out,sheetArray(book,'eGS Standard - CA'),'캐나다','eGS Standard');parseTwoColumn(out,sheetArray(book,'eGS Standard - US'),'미국','eGS Standard');parseTwoColumn(out,sheetArray(book,'eGS Standard - AU'),'호주','eGS Standard');parseEUStandard(out,sheetArray(book,'eGS Standard - EU'));parseExpress(out,book);parseEMS(out,sheetArray(book,'eGS EMS'));return out}
function download(sheets,file){let book=XLSX.utils.book_new();Object.entries(sheets).forEach(([n,r])=>XLSX.utils.book_append_sheet(book,XLSX.utils.json_to_sheet(r),n));XLSX.writeFile(book,file)}
function rateTemplate(){download({'요금표':[{'국가':'미국','서비스':'eGS Standard','최대적용중량kg':1,'배송비원':0},{'국가':'미국','서비스':'eGS Express','최대적용중량kg':1,'배송비원':0},{'국가':'미국','서비스':'eGS EMS','최대적용중량kg':1,'배송비원':0}],'세금규칙':[{'국가':'미국','상품카테고리':'전체','관세율':0,'부가세율':0,'면세한도USD':0}],'안내':[{'설명':'요금표에 국가·서비스별 무게 구간을 모두 입력하세요. 세금규칙의 전체는 국가 기본값입니다.'}]},name('EGS_요금표_양식'))}
function inputTemplate(){download({'상품입력':[{'상품명':'예시 상품','도착국가':'미국, 일본','실중량kg':1,'가로cm':30,'세로cm':20,'높이cm':10,'상품판매가원':100000,'매입가원':40000,'포장비원':2000,'상품카테고리':'일반 상품','수익반영서비스':'eGS Standard','수수료율%':13.6,'고정수수료USD':0.4}],'안내':[{'설명':'도착국가는 쉼표로 여러 국가를 입력할 수 있습니다. 결과는 상품·국가별로 생성됩니다.'}]},name('EGS_상품입력_양식'))}
function bulkRun(){if(!bulk.length||!data.rates.length)return;let output=[];bulk.forEach(row=>clean(key(row,'도착국가','국가')).split(',').map(clean).filter(Boolean).forEach(country=>{let v={country,length:n(key(row,'가로cm','가로')),width:n(key(row,'세로cm','세로')),height:n(key(row,'높이cm','높이')),weight:n(key(row,'실중량kg','실중량')),sale:n(key(row,'상품판매가원','상품판매가')),cost:n(key(row,'매입가원','매입가')),pack:n(key(row,'포장비원','포장비')),category:clean(key(row,'상품카테고리','카테고리'))||'일반 상품',rate:n(key(row,'수수료율%','수수료율'))/100||.136,fixed:n(key(row,'고정수수료usd','고정수수료'))||.4},service=clean(key(row,'수익반영서비스','서비스'))||'eGS Standard',r=calcOne(v,service);output.push({'상품명':key(row,'상품명'),'도착국가':country,'서비스':service,'실중량kg':v.weight,'부피무게kg':Number(r.volume.toFixed(2)),'적용중량kg':r.applied,'예상배송비원':r.cost??'요금없음','eBay수수료원':Math.round(r.fee),'관세부가세원':Math.round(r.t.total),'판매자실수익원':r.profit==null?'요금없음':Math.round(r.profit),'달러환산USD':r.profit==null?'요금없음':Number((r.profit/fx).toFixed(2)),'마진율%':r.margin==null?'요금없음':Number((r.margin*100).toFixed(1)),'적용환율KRWUSD':fx,'세금규칙':r.t.label})}));download({'계산결과':output},name('EGS_계산결과'))}
async function exchange(){try{$('#exchangeStatus').textContent='실시간 환율을 불러오는 중입니다.';let j=await(await fetch('https://open.er-api.com/v6/latest/USD')).json();if(!j?.rates?.KRW)throw 0;fx=n(j.rates.KRW);$('#exchangeValue').textContent=fx.toLocaleString('ko-KR',{maximumFractionDigits:2});$('#exchangeStatus').textContent=`${j.time_last_update_utc?new Date(j.time_last_update_utc).toLocaleString('ko-KR'):'방금'} 기준 자동 환율`;calculate()}catch{$('#exchangeValue').textContent=fx.toLocaleString('ko-KR');$('#exchangeStatus').textContent='자동 환율을 불러오지 못했습니다. 수동 환율을 입력할 수 있습니다.'}}
function init(){options();status();$('#feeSummary').textContent='일반 카테고리 기준 13.60% + 주문당 $0.40 (수정 가능)';$('#calcForm').addEventListener('submit',e=>{e.preventDefault();calculate()});$('#service').addEventListener('change',calculate);$('#feeToggle').onclick=()=>$('#feeFields').hidden=!$('#feeFields').hidden;$('#downloadRateTemplate').onclick=rateTemplate;$('#downloadInputTemplate').onclick=inputTemplate;$('#rateFile').onchange=e=>e.target.files[0]&&read(e.target.files[0],book=>{try{let rates=parseActualEGS(book);if(!rates.length)rates=rows(book,'요금표').map(mapped).filter(r=>r.country&&r.service&&r.maxWeight&&r.shippingCost);if(!rates.length)throw Error('지원하는 EGS 운임표 또는 요금표 시트에 유효한 행이 없습니다.');data={rates,taxes:rows(book,'세금규칙').map(mapped).filter(r=>r.country&&r.category),updated:new Date().toLocaleString('ko-KR')};localStorage.setItem('sellscope-rates',JSON.stringify(data));options();status();$('#rateStatus').textContent=`${e.target.files[0].name}을 불러왔습니다. ${rates.length.toLocaleString()}개 요금 구간이 준비되었습니다.`;calculate()}catch(err){$('#rateStatus').textContent=`불러오지 못했습니다: ${err.message}`}});$('#bulkFile').onchange=e=>e.target.files[0]&&read(e.target.files[0],book=>{bulk=rows(book,'상품입력');$('#bulkStatus').textContent=bulk.length?`${e.target.files[0].name} · ${bulk.length}개 상품을 준비했습니다.`:'상품입력 시트에 데이터가 없습니다.';status()});$('#bulkRun').onclick=bulkRun;$('#clearRates').onclick=()=>{data={rates:[],taxes:[]};localStorage.removeItem('sellscope-rates');options();status();calculate()};$('#refreshExchange').onclick=exchange;$('#applyManualExchange').onclick=()=>{let x=n($('#manualExchange').value);if(x){fx=x;$('#exchangeValue').textContent=x.toLocaleString('ko-KR');$('#exchangeStatus').textContent='수동 입력 환율';calculate()}};$('#themeButton').onclick=()=>document.body.classList.toggle('dark');document.addEventListener('click',e=>{if(e.target.dataset.action==='rates')$('#rates').scrollIntoView({behavior:'smooth'})});exchange()}
init();
